### ISSUE TITLE
Policy definition not working from RabbitMQ 3.8

### ISSUE THREAD

**Issue by ebuildy** [rabbitmq/rabbitmq-sharding#39] opened 2020-07-01 12:13 UTC
We moved from 3.7 to 3.8.5, and got this error at startup:

```
"Validation failed\n\n[{&lt;&lt;\"shards-per-node\"&gt;&gt;,1}] are not recognised policy settings
```

Our ``rabbitmq.definitions.json`` : 

```
...
"policies": [
    {
      "vhost": "/",
      "name": "esx-shard",
      "pattern": "^esx$",
      "definition": {
        "shards-per-node": 1
      }
    },
...
```

This was working fine with RabbitMQ 3.7. Plugin is enabled.

**Comment by lukebakken** [comment] 2020-07-01 12:33
https://github.com/rabbitmq/rabbitmq-server/issues/2177

**Comment by michaelklishin** [comment] 2020-07-01 12:38
Duplicate of https://github.com/rabbitmq/rabbitmq-server/issues/2384.

**Closed by michaelklishin** 2020-07-01 12:38 UTC

**Comment by michaelklishin** [comment] 2020-07-01 12:40
Another example: https://github.com/rabbitmq/rabbitmq-server/issues/2381, all with the same root cause. Starting with `3.8.4` this has only become more visible (affected custom exchange plugins, for example), otherwise, the problem was not new and affected other plugins in 3.7.

**Comment by michaelklishin** [comment] 2020-07-01 12:42
Addressed in https://github.com/rabbitmq/rabbitmq-server/issues/2384 which will ship in `3.8.6`. Those on earlier versions can always [import definitions after node startup](https://www.rabbitmq.com/definitions.html).
